# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lwdlxEhh_FGxa8bmmBc6c2DRCjwUOMd-
"""

!pip install llama-index

!pip install llama-index huggingface_hub

import os
from getpass import getpass
from huggingface_hub import login

HF_TOKEN = getpass(prompt="Enter your Hugging Face token:")

login (token=HF_TOKEN)

!pip install llama_index.readers.web

!pip install llama_index.readers.web
from llama_index.readers.web import SimpleWebPageReader

from llama_index.readers.web import SimpleWebPageReader

documents = SimpleWebPageReader(html_to_text=True).load_data(["https://ohsl.us/projects/bcda"])

documents

!pip install llama_index.llms.huggingface

from llama_index.llms.huggingface import HuggingFaceInferenceAPI

llm = HuggingFaceInferenceAPI(model_name='mistralai/Mixtral-8x7B-Instruct-v0.1', token= HF_TOKEN)
llm

from llama_index.core import SummaryIndex
index = SummaryIndex.from_documents(documents)

index

query_engine = index.as_query_engine(llm=llm)

query_engine

response = query_engine.query("explain about bcda?")

print (response)